/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pl_edu_agh_capo_hough_jni_JniKernelHough */

#ifndef _Included_pl_edu_agh_capo_hough_jni_JniKernelHough
#define _Included_pl_edu_agh_capo_hough_jni_JniKernelHough
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pl_edu_agh_capo_hough_jni_JniKernelHough
 * Method:    kht
 * Signature: ([BJJJDDDD)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_pl_edu_agh_capo_hough_jni_JniKernelHough_kht
  (JNIEnv *, jobject, jbyteArray, jlong, jlong, jint, jlong, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
